name: Build PR Debug APK

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-        

      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew assembleFossReleaseDebug
        env:
          GITHUB_WORKFLOW_RUN_ID: ${{ github.run_id }}

      - uses: actions/upload-artifact@v4
        with:
          name: linksheet-pr-release-debug
          path: app/build/outputs/apk/foss/releaseDebug/*.apk
